// Rust JSON-RPC Library
// Written in 2015 by
//     Andrew Poelstra <apoelstra@wpsoftware.net>
//
// To the extent possible under law, the author(s) have dedicated all
// copyright and related and neighboring rights to this software to
// the public domain worldwide. This software is distributed without
// any warranty.
//
// You should have received a copy of the CC0 Public Domain Dedication
// along with this software.
// If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
//

//! # Client support
//!
//! Support for connecting to JSONRPC servers over HTTP, sending requests,
//! and parsing responses
//!

use std::{error, io};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use serde;
use base64;
use http;
use serde_json;

use super::{Request, Response};
use util::HashableValue;
use error::Error;

/// An interface for an HTTP roundtripper that handles HTTP requests.
pub trait HttpRoundTripper {
    /// The type of the http::Response body.
    type ResponseBody: io::Read;
    /// The type for errors generated by the roundtripper.
    type Err: error::Error;

    /// Make an HTTP request.  In practice only POST request will be made.
    fn post(
        &self,
        http::Request<&[u8]>,
    ) -> Result<http::Response<Self::ResponseBody>, Self::Err>;
}

/// A handle to a remote JSONRPC server
pub struct Client<R: HttpRoundTripper> {
    url: String,
    user: Option<String>,
    pass: Option<String>,
    roundtripper: R,
    nonce: Arc<Mutex<u64>>,
}

impl<Rt: HttpRoundTripper + 'static> Client<Rt> {
    /// Creates a new client
    pub fn new(
        roundtripper: Rt,
        url: String,
        user: Option<String>,
        pass: Option<String>,
    ) -> Client<Rt> {
        // Check that if we have a password, we have a username; other way around is ok
        debug_assert!(pass.is_none() || user.is_some());

        Client {
            url: url,
            user: user,
            pass: pass,
            roundtripper: roundtripper,
            nonce: Arc::new(Mutex::new(0)),
        }
    }

    /// Make a request and deserialize the response
    pub fn do_rpc<T: for<'a> serde::de::Deserialize<'a>>(
        &self,
        rpc_name: &str,
        args: &[serde_json::value::Value],
    ) -> Result<T, Error> {
        let request = self.build_request(rpc_name, args);
        let response = self.send_request(&request)?;

        Ok(response.into_result()?)
    }

    /// The actual send logic used by both [send_request] and [send_batch].
    fn send_raw<B, R>(&self, body: &B) -> Result<R, Error>
    where
        B: serde::ser::Serialize,
        R: for<'de> serde::de::Deserialize<'de>,
    {
        // Build request
        let request_raw = serde_json::to_vec(body)?;

        // Send request
        let mut request_builder = http::Request::post(&self.url);
        request_builder.header("Content-Type", "application/json-rpc");

        // Set Authorization header
        if let Some(ref user) = self.user {
            let mut auth = user.clone();
            auth.push(':');
            if let Some(ref pass) = self.pass {
                auth.push_str(&pass[..]);
            }
            let value = format!("Basic {}", &base64::encode(auth.as_bytes()));
            request_builder.header("Authorization", value);
        }

        // Errors only on invalid header or builder reuse.
        let http_request = request_builder.body(&request_raw[..]).unwrap();

        let http_response =
            self.roundtripper.post(http_request).map_err(|e| Error::Http(Box::new(e)))?;

        // nb we ignore stream.status since we expect the body
        // to contain information about any error
        Ok(serde_json::from_reader(http_response.into_body())?)
    }

    /// Sends a request to a client
    pub fn send_request(&self, request: &Request) -> Result<Response, Error> {
        let response: Response = self.send_raw(&request)?;
        if response.jsonrpc != None && response.jsonrpc != Some(From::from("2.0")) {
            return Err(Error::VersionMismatch);
        }
        if response.id != request.id {
            return Err(Error::NonceMismatch);
        }
        Ok(response)
    }

    /// Sends a batch of requests to the client.  The return vector holds the response
    /// for the request at the corresponding index.  If no response was provided, it's [None].
    ///
    /// Note that the requests need to have valid IDs, so it is advised to create the requests
    /// with [build_request].
    pub fn send_batch(&self, requests: &[Request]) -> Result<Vec<Option<Response>>, Error> {
        if requests.len() < 1 {
            return Err(Error::EmptyBatch);
        }

        // If the request body is invalid JSON, the response is a single response object.
        // We ignore this case since we are confident we are producing valid JSON.
        let responses: Vec<Response> = self.send_raw(&requests)?;
        if responses.len() > requests.len() {
            return Err(Error::WrongBatchResponseSize);
        }

        // To prevent having to clone responses, we first copy all the IDs so we can reference
        // them easily. IDs can only be of JSON type String or Number (or Null), so cloning
        // should be inexpensive and require no allocations as Numbers are more common.
        let ids: Vec<serde_json::Value> = responses.iter().map(|r| r.id.clone()).collect();
        // First index responses by ID and catch duplicate IDs.
        let mut resp_by_id = HashMap::new();
        for (id, resp) in ids.iter().zip(responses.into_iter()) {
            if let Some(dup) = resp_by_id.insert(HashableValue(&id), resp) {
                return Err(Error::BatchDuplicateResponseId(dup.id));
            }
        }
        // Match responses to the requests.
        let results =
            requests.into_iter().map(|r| resp_by_id.remove(&HashableValue(&r.id))).collect();

        // Since we're also just producing the first duplicate ID, we can also just produce the
        // first incorrect ID in case there are multiple.
        if let Some(incorrect) = resp_by_id.into_iter().nth(0) {
            return Err(Error::WrongBatchResponseId(incorrect.1.id));
        }

        Ok(results)
    }

    /// Builds a request
    pub fn build_request<'a, 'b>(
        &self,
        name: &'a str,
        params: &'b [serde_json::Value],
    ) -> Request<'a, 'b> {
        let mut nonce = self.nonce.lock().unwrap();
        *nonce += 1;
        Request {
            method: name,
            params: params,
            id: From::from(*nonce),
            jsonrpc: Some("2.0"),
        }
    }

    /// Accessor for the last-used nonce
    pub fn last_nonce(&self) -> u64 {
        *self.nonce.lock().unwrap()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io;

    struct RT();
    impl HttpRoundTripper for RT {
        type ResponseBody = io::Empty;
        type Err = io::Error;

        fn post(
            &self,
            _: http::Request<&[u8]>,
        ) -> Result<http::Response<Self::ResponseBody>, Self::Err> {
            Err(io::ErrorKind::Other.into())
        }
    }

    #[test]
    fn sanity() {
        let client = Client::new(RT(), "localhost".to_owned(), None, None);
        assert_eq!(client.last_nonce(), 0);
        let req1 = client.build_request("test", &[]);
        assert_eq!(client.last_nonce(), 1);
        let req2 = client.build_request("test", &[]);
        assert_eq!(client.last_nonce(), 2);
        assert!(req1 != req2);
    }
}
